(bind-key* "C-h" 'delete-backward-char)
(bind-key* "C-k" 'kill-whole-line)
(bind-key* "C-c <left>"  'windmove-left)
(bind-key* "C-c <down>"  'windmove-down)
(bind-key* "C-c <up>"    'windmove-up)
(bind-key* "C-c <right>" 'windmove-right)
